const KEYS={pin:'loja-admin-pin-v1',notes:'loja-admin-notes-v1',expenses:'loja-admin-expenses-v2',categories:'loja-admin-expense-categories-v1',withdrawals:'loja-admin-withdrawals-v1',sales:'loja-pos-sales-v1',products:'loja-pos-products-v1',balances:'loja-admin-balances-v1',movements:'loja-admin-balance-movements-v1'};
const DEFAULT_CATEGORIES=['Pró-labore — Caio','Pró-labore — Pai','Retirada de sócio','Vale de funcionário','Salário e encargos','Fornecedor','Energia elétrica','Água','Aluguel','Internet e telefone','Impostos e taxas','Manutenção da loja','Café e alimentação','Despesa desnecessária','Outros'];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),$=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parseMoney=v=>{let s=String(v??'').trim().replace(/[^\d,.-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?Math.max(0,n):0};
const localDate=value=>{const d=value?new Date(value.length===10?value+'T12:00:00':value):new Date();return Number.isNaN(d.getTime())?new Date():d};
const isoToday=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)},dateLabel=value=>localDate(value).toLocaleDateString('pt-BR');
async function hash(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
let expenses=loadExpenses(),categories=loadCategories(),movements=read(KEYS.movements,[]);
function loadCategories(){const saved=read(KEYS.categories,null);if(Array.isArray(saved)&&saved.length)return saved;save(KEYS.categories,DEFAULT_CATEGORIES);return[...DEFAULT_CATEGORIES]}
function loadExpenses(){const current=read(KEYS.expenses,null);if(Array.isArray(current))return current;const migrated=read(KEYS.withdrawals,[]).map(x=>({id:x.id||crypto.randomUUID(),category:'Retirada de sócio',payee:x.partner||'Sócio',description:x.reason||'Retirada',amount:Number(x.amount||0),date:x.date||isoToday(),payment:'Outro',status:'Pago',recurring:false,notes:'Migrado do controle anterior',createdAt:x.createdAt||new Date().toISOString()}));save(KEYS.expenses,migrated);return migrated}
function setupLock(){const hasPin=Boolean(localStorage.getItem(KEYS.pin));$('#lockTitle').textContent=hasPin?'Administrativo':'Crie seu PIN';$('#lockText').textContent=hasPin?'Entre com seu PIN para acessar as informações de gestão.':'Escolha um PIN que somente você saiba. Ele será pedido sempre que esta área for aberta.';$('#confirmField').hidden=hasPin;$('#pinConfirm').required=!hasPin;$('#pinSubmit').textContent=hasPin?'Entrar':'Criar PIN e entrar'}
function unlock(){sessionStorage.setItem('loja-admin-unlocked','1');$('#lockScreen').hidden=true;$('#adminApp').hidden=false;render()}
$('#pinForm').onsubmit=async e=>{e.preventDefault();const pin=$('#pinInput').value,stored=localStorage.getItem(KEYS.pin);if(!stored){if(pin!==$('#pinConfirm').value){$('#pinHelp').textContent='Os PINs não são iguais.';return}localStorage.setItem(KEYS.pin,await hash(pin));unlock();return}if(await hash(pin)!==stored){$('#pinHelp').textContent='PIN incorreto. Tente novamente.';$('#pinInput').select();return}unlock()};
$('#lockBtn').onclick=()=>{sessionStorage.removeItem('loja-admin-unlocked');location.reload()};
function startOfDay(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}function startOfWeek(){const d=startOfDay(),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d}function startOfMonth(){const d=startOfDay();d.setDate(1);return d}
function inPeriod(value,period){const d=localDate(value);if(period==='all')return true;if(period==='today')return d>=startOfDay();if(period==='week')return d>=startOfWeek();return d>=startOfMonth()}
function saleCost(sale){return(sale.items||[]).reduce((sum,item)=>sum+Number(item.cost||0)*Number(item.qty||1),0)}function sum(list,field='amount'){return list.reduce((total,item)=>total+Number(item[field]||0),0)}function plural(count,one,many){return count===1?one:many}
function render(){const sales=read(KEYS.sales,[]),products=read(KEYS.products,[]),paid=expenses.filter(x=>x.status!=='Pendente'),daySales=sales.filter(x=>inPeriod(x.createdAt,'today')),weekSales=sales.filter(x=>inPeriod(x.createdAt,'week')),monthSales=sales.filter(x=>inPeriod(x.createdAt,'month'));const setSales=(prefix,list)=>{$('#sales'+prefix).textContent=money.format(sum(list,'total'));$('#sales'+prefix+'Count').textContent=`${list.length} ${plural(list.length,'venda','vendas')}`};setSales('Today',daySales);setSales('Week',weekSales);setSales('Month',monthSales);const revenue=sum(monthSales,'total'),gross=monthSales.reduce((s,x)=>s+Number(x.total||0)-saleCost(x),0),monthPaid=paid.filter(x=>inPeriod(x.date,'month')),expenseTotal=sum(monthPaid),result=gross-expenseTotal;$('#grossProfit').textContent=money.format(gross);$('#grossMargin').textContent=`Margem ${revenue?(gross/revenue*100).toFixed(1).replace('.',','):0}%`;$('#monthExpenses').textContent=money.format(expenseTotal);$('#monthExpenseCount').textContent=`${monthPaid.length} ${plural(monthPaid.length,'lançamento','lançamentos')}`;$('#monthResult').textContent=money.format(result);$('#monthResult').classList.toggle('negative',result<0);const stock=products.filter(x=>x.trackStock!==false),stockValue=stock.reduce((s,x)=>s+Number(x.cost||0)*Number(x.stock||0),0);$('#stockValue').textContent=money.format(stockValue);$('#stockCount').textContent=`Custo de compra de ${stock.length} ${plural(stock.length,'produto','produtos')} em estoque`;$('#lowStock').textContent=stock.filter(x=>Number(x.stock||0)<=Number(x.minStock||0)).length;renderBalances(sales,paid);renderBreakdown(monthPaid);renderPartners(monthPaid);renderCategoryFilter();renderExpenses()}
function isCashPayment(value=''){return String(value).toLocaleLowerCase('pt-BR').includes('dinheiro')}
function balanceState(sales,paid){const base=read(KEYS.balances,null);if(!base)return null;const since=new Date(base.at).getTime(),afterBase=value=>localDate(value).getTime()>=since;let cash=Number(base.cash||0),bank=Number(base.bank||0);sales.filter(x=>afterBase(x.createdAt)).forEach(x=>{if(isCashPayment(x.payment))cash+=Number(x.total||0);else bank+=Number(x.total||0)});paid.filter(x=>afterBase(x.createdAt||x.date)).forEach(x=>{if(isCashPayment(x.payment))cash-=Number(x.amount||0);else bank-=Number(x.amount||0)});movements.filter(x=>afterBase(x.createdAt||x.date)).forEach(x=>{const amount=Number(x.amount||0);if(x.type==='entry')x.account==='cash'?cash+=amount:bank+=amount;if(x.type==='withdrawal')x.account==='cash'?cash-=amount:bank-=amount;if(x.type==='transfer'){x.account==='cash'?(cash-=amount,bank+=amount):(bank-=amount,cash+=amount)}});return{cash,bank,total:cash+bank,base}}
function renderBalances(sales,paid){const state=balanceState(sales,paid);if(!state){$('#cashBalance').textContent=$('#bankBalance').textContent=$('#totalBalance').textContent='—';$('#balanceUpdated').textContent='Informe os saldos atuais para começar o controle.';$('#movementList').innerHTML='<div class="empty compact">Nenhum saldo configurado.</div>';$('#balanceWarning').hidden=true;return}$('#cashBalance').textContent=money.format(state.cash);$('#bankBalance').textContent=money.format(state.bank);$('#totalBalance').textContent=money.format(state.total);$('#balanceUpdated').textContent=`Calculado desde ${new Date(state.base.at).toLocaleString('pt-BR')}`;const negatives=[];if(state.cash<0)negatives.push('o caixa em dinheiro');if(state.bank<0)negatives.push('a conta bancária');$('#balanceWarning').hidden=!negatives.length;$('#balanceWarning').textContent=negatives.length?`Atenção: ${negatives.join(' e ')} ficou negativo. Confira lançamentos ou redefina os saldos atuais.`:'';renderMovements()}
function renderMovements(showAll=false){const list=[...movements].sort((a,b)=>localDate(b.createdAt||b.date)-localDate(a.createdAt||a.date));const visible=showAll?list:list.slice(0,5);const labels={entry:'Entrada manual',withdrawal:'Retirada',transfer:'Transferência'};$('#movementList').innerHTML=visible.length?visible.map(x=>`<article class="movement-row"><div><strong>${esc(x.description)}</strong><span>${labels[x.type]} • ${x.account==='cash'?'Caixa':'Banco'}${x.type==='transfer'?` → ${x.destination==='cash'?'Caixa':'Banco'}`:''}</span></div><time>${dateLabel(x.date)}</time><b class="${x.type==='withdrawal'?'out':'in'}">${x.type==='withdrawal'?'−':x.type==='entry'?'+':''} ${money.format(x.amount)}</b><button data-delete-movement="${esc(x.id)}" aria-label="Excluir movimentação">×</button></article>`).join(''):'<div class="empty compact">As movimentações manuais aparecerão aqui.</div>';document.querySelectorAll('[data-delete-movement]').forEach(button=>button.onclick=()=>{if(!confirm('Excluir esta movimentação de saldo?'))return;movements=movements.filter(x=>x.id!==button.dataset.deleteMovement);save(KEYS.movements,movements);render();toast('Movimentação excluída')})}
function categoryGroup(category='Outros'){if(category.startsWith('Pró-labore')||category==='Retirada de sócio')return'Pró-labore e sócios';if(category.includes('funcionário')||category==='Salário e encargos')return'Funcionários';if(category==='Fornecedor')return'Fornecedores';if(['Energia elétrica','Água','Aluguel','Internet e telefone','Impostos e taxas','Manutenção da loja'].includes(category))return'Contas da loja';if(['Café e alimentação','Despesa desnecessária'].includes(category))return'Despesas pequenas';return'Outros'}
function renderBreakdown(list){const groups={};list.forEach(x=>{const group=categoryGroup(x.category);groups[group]=(groups[group]||0)+Number(x.amount||0)});const total=sum(list);$('#expenseBreakdown').innerHTML=Object.keys(groups).length?Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="breakdown-row"><div><strong>${esc(name)}</strong><span>${total?Math.round(value/total*100):0}% das saídas</span></div><b>${money.format(value)}</b></div>`).join(''):'<div class="empty">Nenhuma saída paga neste mês.</div>'}
function renderPartners(list){const groups={};list.filter(x=>categoryGroup(x.category)==='Pró-labore e sócios').forEach(x=>{const name=x.category.startsWith('Pró-labore —')?x.category.split('—')[1].trim():(x.payee||'Sócio');groups[name]=(groups[name]||0)+Number(x.amount||0)});$('#partnerSummary').innerHTML=Object.keys(groups).length?Object.entries(groups).map(([name,value])=>`<div class="partner-row"><span>${esc(name)}</span><strong>${money.format(value)}</strong></div>`).join(''):'<div class="empty">Nenhum pró-labore ou retirada neste mês.</div>'}
function renderCategoryFilter(){const select=$('#categoryFilter'),current=select.value||'all',options=[...new Set([...categories,...expenses.map(x=>x.category).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'pt-BR'));select.innerHTML='<option value="all">Todas as categorias</option>'+options.map(x=>`<option>${esc(x)}</option>`).join('');select.value=options.includes(current)?current:'all'}
function populateExpenseCategories(selected=''){const select=$('#expenseCategory');select.innerHTML='<option value="">Selecione</option>'+categories.map(x=>`<option>${esc(x)}</option>`).join('');if(selected&&!categories.includes(selected))select.insertAdjacentHTML('beforeend',`<option>${esc(selected)}</option>`);select.value=selected}
function filteredExpenses(){const period=$('#periodFilter').value,category=$('#categoryFilter').value,q=$('#expenseSearch').value.trim().toLocaleLowerCase('pt-BR');return expenses.filter(x=>inPeriod(x.date,period)&&(category==='all'||x.category===category)&&(!q||`${x.payee} ${x.description} ${x.notes} ${x.category}`.toLocaleLowerCase('pt-BR').includes(q))).sort((a,b)=>localDate(b.date)-localDate(a.date)||String(b.createdAt).localeCompare(String(a.createdAt)))}
function renderExpenses(){const list=filteredExpenses();$('#filteredExpenseTotal').textContent=money.format(sum(list));$('#expenseList').innerHTML=list.length?list.map(x=>`<article class="expense-row"><span class="category-badge">${esc(x.category)}</span><div class="expense-main"><strong>${esc(x.description)}</strong><span>${esc(x.payee)} • ${esc(x.payment||'Não informado')}${x.recurring?' • Recorrente':''}</span></div><time>${dateLabel(x.date)}</time><span class="status ${x.status==='Pendente'?'pending':''}">${esc(x.status||'Pago')}</span><b>${money.format(x.amount)}</b><button class="edit-button" data-edit="${esc(x.id)}">Editar</button></article>`).join(''):'<div class="empty">Nenhuma saída encontrada neste período.</div>';document.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>openExpense(button.dataset.edit))}
function openExpense(id=null){$('#expenseForm').reset();populateExpenseCategories();$('#expenseId').value='';$('#expenseDate').value=isoToday();$('#expenseModalTitle').textContent='Nova saída';$('#deleteExpense').hidden=true;if(id){const item=expenses.find(x=>x.id===id);if(!item)return;$('#expenseId').value=item.id;populateExpenseCategories(item.category);$('#expensePayee').value=item.payee;$('#expenseDescription').value=item.description;$('#expenseAmount').value=Number(item.amount||0).toLocaleString('pt-BR',{minimumFractionDigits:2});$('#expenseDate').value=item.date;$('#expensePayment').value=item.payment||'Pix';$('#expenseStatus').value=item.status||'Pago';$('#expenseRecurring').checked=Boolean(item.recurring);$('#expenseNotes').value=item.notes||'';$('#expenseModalTitle').textContent='Editar saída';$('#deleteExpense').hidden=false}$('#expenseDialog').showModal()}
$('#expenseForm').onsubmit=e=>{e.preventDefault();const id=$('#expenseId').value,data={category:$('#expenseCategory').value,payee:$('#expensePayee').value.trim(),description:$('#expenseDescription').value.trim(),amount:parseMoney($('#expenseAmount').value),date:$('#expenseDate').value,payment:$('#expensePayment').value,status:$('#expenseStatus').value,recurring:$('#expenseRecurring').checked,notes:$('#expenseNotes').value.trim()};if(id)Object.assign(expenses.find(x=>x.id===id),data,{updatedAt:new Date().toISOString()});else expenses.unshift({id:crypto.randomUUID(),...data,createdAt:new Date().toISOString()});save(KEYS.expenses,expenses);$('#expenseDialog').close();render();toast(id?'Saída atualizada':'Saída registrada')};
$('#deleteExpense').onclick=()=>{const id=$('#expenseId').value;if(!id||!confirm('Excluir este lançamento financeiro?'))return;expenses=expenses.filter(x=>x.id!==id);save(KEYS.expenses,expenses);$('#expenseDialog').close();render();toast('Lançamento excluído')};
function renderCategoryManager(){$('#categoryManagerList').innerHTML=categories.map((name,index)=>`<div class="category-manager-row"><input value="${esc(name)}" maxlength="60" data-category-name="${index}"><button type="button" class="save-category" data-save-category="${index}">Salvar</button><button type="button" class="delete-category" data-delete-category="${index}">Excluir</button></div>`).join('');document.querySelectorAll('[data-save-category]').forEach(button=>button.onclick=()=>renameCategory(Number(button.dataset.saveCategory)));document.querySelectorAll('[data-delete-category]').forEach(button=>button.onclick=()=>deleteCategory(Number(button.dataset.deleteCategory)))}
function renameCategory(index){const input=document.querySelector(`[data-category-name="${index}"]`),next=input.value.trim(),previous=categories[index];if(!next){toast('Digite um nome para a categoria');input.focus();return}if(categories.some((x,i)=>i!==index&&x.toLocaleLowerCase('pt-BR')===next.toLocaleLowerCase('pt-BR'))){toast('Essa categoria já existe');return}categories[index]=next;expenses.forEach(item=>{if(item.category===previous)item.category=next});save(KEYS.categories,categories);save(KEYS.expenses,expenses);renderCategoryManager();render();toast('Categoria atualizada')}
function deleteCategory(index){const name=categories[index],used=expenses.filter(x=>x.category===name).length;if(name==='Outros'){toast('A categoria Outros não pode ser excluída');return}if(used&&!confirm(`Esta categoria possui ${used} lançamento(s). Ao excluir, eles serão movidos para “Outros”. Continuar?`))return;expenses.forEach(item=>{if(item.category===name)item.category='Outros'});categories.splice(index,1);save(KEYS.categories,categories);save(KEYS.expenses,expenses);renderCategoryManager();render();toast('Categoria excluída')}
$('#categoryForm').onsubmit=e=>{e.preventDefault();const input=$('#newCategoryName'),name=input.value.trim();if(!name){input.focus();return}if(categories.some(x=>x.toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR'))){toast('Essa categoria já existe');return}categories.push(name);categories.sort((a,b)=>a.localeCompare(b,'pt-BR'));save(KEYS.categories,categories);input.value='';renderCategoryManager();renderCategoryFilter();toast('Categoria adicionada')};
$('#manageCategoriesBtn').onclick=()=>{renderCategoryManager();$('#newCategoryName').value='';$('#categoryDialog').showModal()};$('#closeCategories').onclick=()=>$('#categoryDialog').close();
$('#newExpenseBtn').onclick=$('#newExpenseBtn2').onclick=()=>openExpense();$('#closeExpense').onclick=$('#cancelExpense').onclick=()=>$('#expenseDialog').close();$('#periodFilter').onchange=$('#categoryFilter').onchange=renderExpenses;$('#expenseSearch').oninput=renderExpenses;$('#clearFilters').onclick=()=>{$('#periodFilter').value='month';$('#categoryFilter').value='all';$('#expenseSearch').value='';renderExpenses()};
$('#privateNotes').value=localStorage.getItem(KEYS.notes)||'';$('#privateNotes').oninput=()=>localStorage.setItem(KEYS.notes,$('#privateNotes').value);function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function openBalances(){const current=balanceState(read(KEYS.sales,[]),expenses.filter(x=>x.status!=='Pendente'));$('#baseCash').value=current?current.cash.toLocaleString('pt-BR',{minimumFractionDigits:2}):'';$('#baseBank').value=current?current.bank.toLocaleString('pt-BR',{minimumFractionDigits:2}):'';$('#balanceDialog').showModal()}
$('#setBalancesBtn').onclick=openBalances;$('#closeBalances').onclick=$('#cancelBalances').onclick=()=>$('#balanceDialog').close();$('#balanceForm').onsubmit=e=>{e.preventDefault();save(KEYS.balances,{cash:parseMoney($('#baseCash').value),bank:parseMoney($('#baseBank').value),at:new Date().toISOString()});$('#balanceDialog').close();render();toast('Saldos atuais salvos')};
function updateMovementFields(){const transfer=$('#movementType').value==='transfer';$('#movementDestinationField').hidden=!transfer;if(transfer){$('#movementDestination').value=$('#movementAccount').value==='cash'?'bank':'cash'}}
$('#newMovementBtn').onclick=()=>{$('#movementForm').reset();$('#movementDate').value=isoToday();updateMovementFields();$('#movementDialog').showModal()};$('#closeMovement').onclick=$('#cancelMovement').onclick=()=>$('#movementDialog').close();$('#movementType').onchange=updateMovementFields;$('#movementAccount').onchange=updateMovementFields;$('#movementForm').onsubmit=e=>{e.preventDefault();const amount=parseMoney($('#movementAmount').value);if(!amount){toast('Informe um valor maior que zero');return}movements.unshift({id:crypto.randomUUID(),type:$('#movementType').value,account:$('#movementAccount').value,destination:$('#movementDestination').value,amount,date:$('#movementDate').value,description:$('#movementDescription').value.trim(),createdAt:new Date().toISOString()});save(KEYS.movements,movements);$('#movementDialog').close();render();toast('Movimentação registrada')};$('#showAllMovements').onclick=()=>renderMovements(true);
if(sessionStorage.getItem('loja-admin-unlocked')==='1')unlock();else setupLock();
